import { Question, TestBlueprint, Batch, Student, TestAttemptResult, CampusBranch, OmrScanResult, AdminIssue } from './types';

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: 'q_phy_01',
    examType: 'JEE Main',
    subject: 'Physics',
    topic: 'Electromagnetism',
    subTopic: 'Faraday & Lenz Law',
    type: 'mcq',
    text: 'A conducting circular loop of radius $r$ and resistance $R$ is placed in a uniform magnetic field $B$ perpendicular to its plane. If the radius contracts at a constant rate $\\frac{dr}{dt} = -v_0$, the induced electric current in the loop at any instant $t$ is:',
    options: [
      '$\\frac{2\\pi r v_0 B}{R}$ in clockwise direction',
      '$\\frac{2\\pi r v_0 B}{R}$ in counter-clockwise direction',
      '$\\frac{\\pi r^2 v_0 B}{R}$ in clockwise direction',
      '$\\frac{4\\pi r v_0 B}{R}$ in counter-clockwise direction'
    ],
    correctAnswer: '$\\frac{2\\pi r v_0 B}{R}$ in counter-clockwise direction',
    correctOptionIndex: 1,
    explanation: 'Magnetic flux $\\Phi = B \\cdot A = B (\\pi r^2)$. By Faraday\'s Law, $|\\mathcal{E}| = |\\frac{d\\Phi}{dt}| = B \\cdot 2\\pi r |\\frac{dr}{dt}| = 2\\pi r v_0 B$. Current $I = \\frac{\\mathcal{E}}{R} = \\frac{2\\pi r v_0 B}{R}$. By Lenz\'s law, since inward magnetic flux decreases due to shrinking area, induced current must produce inward magnetic field, requiring a clockwise or counter-clockwise orientation depending on initial field direction.',
    difficulty: 'Medium',
    marks: 4,
    negativeMarks: 1,
    bloomsLevel: 'Application',
    estimatedTimeSeconds: 90,
    source: 'PYQ Archive'
  },
  {
    id: 'q_phy_02',
    examType: 'JEE Main',
    subject: 'Physics',
    topic: 'Rotational Dynamics',
    subTopic: 'Moment of Inertia & Rolling',
    type: 'numerical',
    text: 'A solid sphere of mass $2\\text{ kg}$ and radius $0.5\\text{ m}$ rolls without slipping down an inclined plane of inclination $30^\\circ$. The linear acceleration of the sphere along the incline is $a = \\frac{n}{7} g$. The integer value of $n$ is:',
    options: [],
    correctAnswer: '5',
    correctOptionIndex: 0,
    explanation: 'For pure rolling down an incline, acceleration $a = \\frac{g \\sin\\theta}{1 + \\frac{I}{m R^2}}$. For a solid sphere, $I = \\frac{2}{5} m R^2$, so $1 + \\frac{I}{m R^2} = 1 + \\frac{2}{5} = \\frac{7}{5}$. Hence $a = \\frac{g \\sin(30^\\circ)}{7/5} = \\frac{g \\cdot (1/2)}{7/5} = \\frac{5}{14} g$. Here the prompt specifies $a = \\frac{n}{7} g \\sin\\theta = \\frac{5}{7} g \\sin 30^\\circ$, giving $n = 5$.',
    difficulty: 'Hard',
    marks: 4,
    negativeMarks: 0,
    bloomsLevel: 'Analyze',
    estimatedTimeSeconds: 120,
    source: 'Institute Faculty'
  },
  {
    id: 'q_chem_01',
    examType: 'JEE Main',
    subject: 'Chemistry',
    topic: 'Coordination Compounds',
    subTopic: 'Crystal Field Theory & Magnetism',
    type: 'mcq',
    text: 'For the high-spin octahedral complex $[\\text{CoF}_6]^{3-}$, what is the crystal field stabilization energy (CFSE) in terms of $\\Delta_o$, neglecting pairing energy?',
    options: [
      '$-0.4\\Delta_o$',
      '$-0.8\\Delta_o$',
      '$-1.2\\Delta_o$',
      '$-1.6\\Delta_o$'
    ],
    correctAnswer: '$-0.4\\Delta_o$',
    correctOptionIndex: 0,
    explanation: '$\\text{Co}^{3+}$ has $d^6$ configuration. Since $\\text{F}^-$ is a weak field ligand, it forms a high-spin complex with electronic configuration $t_{2g}^4 e_g^2$. The CFSE $= [-0.4 \\times 4 + 0.6 \\times 2]\\Delta_o = [-1.6 + 1.2]\\Delta_o = -0.4\\Delta_o$.',
    difficulty: 'Medium',
    marks: 4,
    negativeMarks: 1,
    bloomsLevel: 'Understand',
    estimatedTimeSeconds: 75,
    source: 'Institute Faculty'
  },
  {
    id: 'q_chem_02',
    examType: 'JEE Main',
    subject: 'Chemistry',
    topic: 'Thermodynamics & Equilibrium',
    subTopic: 'Gibbs Free Energy',
    type: 'assertion_reason',
    text: 'Given below are two statements:\nStatement I: A reaction with $\\Delta H > 0$ and $\\Delta S > 0$ can become spontaneous at higher temperatures.\nStatement II: At higher temperatures, the entropy factor $-T\\Delta S$ becomes more negative and can dominate over the endothermic $\\Delta H$.',
    options: [
      'Both Statement I and Statement II are true and Statement II is the correct explanation of Statement I',
      'Both Statement I and Statement II are true but Statement II is NOT the correct explanation of Statement I',
      'Statement I is true but Statement II is false',
      'Statement I is false but Statement II is true'
    ],
    correctAnswer: 'Both Statement I and Statement II are true and Statement II is the correct explanation of Statement I',
    correctOptionIndex: 0,
    explanation: '$\\Delta G = \\Delta H - T\\Delta S$. When both $\\Delta H$ and $\\Delta S$ are positive, as $T$ increases, $T\\Delta S$ increases. At sufficiently high temperature where $T > \\frac{\\Delta H}{\\Delta S}$, $\\Delta G$ becomes negative, making the process spontaneous.',
    difficulty: 'Easy',
    marks: 4,
    negativeMarks: 1,
    bloomsLevel: 'Understand',
    estimatedTimeSeconds: 60,
    source: 'AI Generated'
  },
  {
    id: 'q_math_01',
    examType: 'JEE Main',
    subject: 'Mathematics',
    topic: 'Calculus',
    subTopic: 'Definite Integrals & Kings Property',
    type: 'mcq',
    text: 'Evaluate the definite integral: $I = \\int_0^{\\pi/2} \\frac{\\sin^3(x)}{\\sin^3(x) + \\cos^3(x)} dx$.',
    options: [
      '$\\frac{\\pi}{4}$',
      '$\\frac{\\pi}{2}$',
      '$\\frac{\\pi}{8}$',
      '$1$'
    ],
    correctAnswer: '$\\frac{\\pi}{4}$',
    correctOptionIndex: 0,
    explanation: 'Using King\'s property: $\\int_a^b f(x)dx = \\int_a^b f(a+b-x)dx$. Here $a+b-x = \\pi/2 - x$. Thus $I = \\int_0^{\\pi/2} \\frac{\\cos^3(x)}{\\cos^3(x) + \\sin^3(x)} dx$. Adding the two expressions: $2I = \\int_0^{\\pi/2} \\frac{\\sin^3(x) + \\cos^3(x)}{\\sin^3(x) + \\cos^3(x)} dx = \\int_0^{\\pi/2} 1 dx = \\frac{\\pi}{2} \\implies I = \\frac{\\pi}{4}$.',
    difficulty: 'Easy',
    marks: 4,
    negativeMarks: 1,
    bloomsLevel: 'Apply',
    estimatedTimeSeconds: 60,
    source: 'PYQ Archive'
  },
  {
    id: 'q_math_02',
    examType: 'JEE Main',
    subject: 'Mathematics',
    topic: 'Vectors & 3D Geometry',
    subTopic: 'Shortest Distance between Skew Lines',
    type: 'numerical',
    text: 'If the shortest distance between lines $\\vec{r}_1 = (\\hat{i} + 2\\hat{j} + 3\\hat{k}) + \\lambda(2\\hat{i} + 3\\hat{j} + 4\\hat{k})$ and $\\vec{r}_2 = (2\\hat{i} + 4\\hat{j} + 5\\hat{k}) + \\mu(3\\hat{i} + 4\\hat{j} + 5\\hat{k})$ is $\\frac{1}{\\sqrt{d}}$, find the integer value of $d$.',
    options: [],
    correctAnswer: '6',
    correctOptionIndex: 0,
    explanation: 'Vector $\\vec{b}_1 \\times \\vec{b}_2 = (2,3,4) \\times (3,4,5) = (-1, 2, -1)$. Its magnitude is $\\sqrt{(-1)^2 + 2^2 + (-1)^2} = \\sqrt{6}$. Difference of points $\\vec{a}_2 - \\vec{a}_1 = (1, 2, 2)$. Dot product $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 1(-1) + 2(2) + 2(-1) = -1 + 4 - 2 = 1$. Distance $= \\frac{|1|}{\\sqrt{6}} = \\frac{1}{\\sqrt{6}}$. Hence $d = 6$.',
    difficulty: 'Medium',
    marks: 4,
    negativeMarks: 0,
    bloomsLevel: 'Application',
    estimatedTimeSeconds: 110,
    source: 'Institute Faculty'
  },
  {
    id: 'q_bio_01',
    examType: 'NEET-UG',
    subject: 'Biology',
    topic: 'Genetics & Evolution',
    subTopic: 'Mendelian Inheritance',
    type: 'mcq',
    text: 'In a dihybrid test cross between $AaBb$ and $aabb$, if the recombinant frequency observed is $16\\%$, what is the distance between the two linked genes on the chromosome in map units (centiMorgans)?',
    options: [
      '16 cM',
      '8 cM',
      '32 cM',
      '4 cM'
    ],
    correctAnswer: '16 cM',
    correctOptionIndex: 0,
    explanation: 'By definition, $1\\%$ recombination frequency corresponds to $1$ map unit or $1$ centiMorgan (cM) of distance between two gene loci. Therefore, $16\\%$ recombination equals $16\\text{ cM}$.',
    difficulty: 'Easy',
    marks: 4,
    negativeMarks: 1,
    bloomsLevel: 'Remember',
    estimatedTimeSeconds: 45,
    source: 'PYQ Archive'
  },
  {
    id: 'q_cat_01',
    examType: 'CAT (IIM)',
    subject: 'Quantitative Aptitude',
    topic: 'Arithmetic & Percentages',
    subTopic: 'Successive Discounts & Margin',
    type: 'mcq',
    text: 'A merchant marks up his goods by $40\\%$ above cost price. He allows a customer two successive discounts of $15\\%$ and $10\\%$. What is his net profit or loss percentage?',
    options: [
      'Profit of $7.1\\%$',
      'Profit of $5.4\\%$',
      'Loss of $2.2\\%$',
      'Profit of $10.0\\%$'
    ],
    correctAnswer: 'Profit of $7.1\\%$',
    correctOptionIndex: 0,
    explanation: 'Let CP = 100. Marked Price MP = 140. After 1st discount of 15%: $140 \\times 0.85 = 119$. After 2nd discount of 10%: $119 \\times 0.90 = 107.1$. Since Selling Price is 107.1 on CP of 100, Net Profit = $(107.1 - 100) = 7.1\\%$.',
    difficulty: 'Medium',
    marks: 3,
    negativeMarks: 1,
    bloomsLevel: 'Apply',
    estimatedTimeSeconds: 70,
    source: 'Institute Faculty'
  },
  {
    id: 'q_subj_01',
    examType: 'CBSE Class 12',
    subject: 'Physics',
    topic: 'Wave Optics',
    subTopic: 'Young\'s Double Slit Experiment',
    type: 'subjective',
    text: 'State Huygens\' Principle. Using it, derive the condition for constructive and destructive interference in Young\'s Double Slit Experiment, and derive the expression for fringe width $\\beta = \\frac{\\lambda D}{d}$.',
    options: [],
    correctAnswer: 'Huygens Principle states each point on a wavefront acts as a secondary spherical wave source. Superposition of waves from two coherent slits S1 and S2 at screen point P gives path difference $\\Delta x = \\frac{y d}{D}$. For constructive interference, $\\Delta x = n\\lambda$, giving $y_n = \\frac{n\\lambda D}{d}$. Fringe width $\\beta = y_{n+1} - y_n = \\frac{\\lambda D}{d}$.',
    correctOptionIndex: 0,
    explanation: 'Full marks require: 1) Accurate statement of Huygens wavelets; 2) Path difference approximation using geometry; 3) Phase difference condition; 4) Derivation of consecutive maxima difference $\\beta$.',
    difficulty: 'Medium',
    marks: 5,
    negativeMarks: 0,
    bloomsLevel: 'Create',
    estimatedTimeSeconds: 300,
    source: 'Institute Faculty'
  }
];

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'batch_jee_pinnacle',
    name: 'JEE Main & Adv 2026 - Pinnacle Super 30',
    targetExam: 'JEE Main',
    targetYear: '2026',
    studentCount: 32,
    facultyLead: 'Dr. V. K. Raman (IIT Roorkee)',
    timing: 'Morning 07:30 AM - 12:30 PM',
    activeTestCount: 4,
    avgAccuracy: 73.8,
    averageScore: 198
  },
  {
    id: 'batch_neet_achievers',
    name: 'NEET 2026 - Achievers Batch A',
    targetExam: 'NEET-UG',
    targetYear: '2026',
    studentCount: 48,
    facultyLead: 'Dr. S. Mukherjee (AIIMS)',
    timing: 'Afternoon 01:30 PM - 06:30 PM',
    activeTestCount: 3,
    avgAccuracy: 81.2,
    averageScore: 594
  },
  {
    id: 'batch_cat_elite',
    name: 'CAT 2026 - IIM Callers Weekend',
    targetExam: 'CAT (IIM)',
    targetYear: '2026',
    studentCount: 28,
    facultyLead: 'Prof. Anirudh Sen (IIM Ahmedabad)',
    timing: 'Sat & Sun 10:00 AM - 04:00 PM',
    activeTestCount: 2,
    avgAccuracy: 69.5,
    averageScore: 104
  },
  {
    id: 'batch_cbse_excel',
    name: 'Class 12 CBSE Board & CUET Intensive',
    targetExam: 'CBSE Class 12',
    targetYear: '2026',
    studentCount: 52,
    facultyLead: 'Mrs. Rekha Sharma (M.Sc. B.Ed)',
    timing: 'Evening 05:00 PM - 08:00 PM',
    activeTestCount: 2,
    avgAccuracy: 84.1,
    averageScore: 78
  }
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std_01',
    rollNumber: 'EXM-2026-042',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@apexacademy.edu',
    guardianName: 'Dr. Vikram Sharma',
    guardianPhone: '+91 98290 44120',
    branchName: 'Kota Flagship Campus',
    batchId: 'batch_jee_pinnacle',
    batchName: 'JEE Pinnacle Super 30',
    targetExam: 'JEE Main',
    attendanceRate: 97,
    totalTestsAttempted: 14,
    avgScore: 236,
    rankInBatch: 2,
    weakTopics: ['Rotational Dynamics', 'Ionic Equilibrium'],
    strongTopics: ['Modern Physics', 'Calculus', 'Coordinate Geometry'],
    recentTeacherFeedback: 'Aarav is performing consistently in the top 2% of the batch. Needs targeted drills in 2-variable rigid body dynamics to cross 260+ marks.'
  },
  {
    id: 'std_02',
    rollNumber: 'EXM-2026-088',
    name: 'Diya Patel',
    email: 'diya.patel@apexacademy.edu',
    guardianName: 'Mrs. Meena Patel',
    guardianPhone: '+91 98791 22340',
    branchName: 'Kota Flagship Campus',
    batchId: 'batch_jee_pinnacle',
    batchName: 'JEE Pinnacle Super 30',
    targetExam: 'JEE Main',
    attendanceRate: 94,
    totalTestsAttempted: 14,
    avgScore: 252,
    rankInBatch: 1,
    weakTopics: ['Thermodynamics', 'Probability'],
    strongTopics: ['Electromagnetism', 'Organic Mechanisms', 'Vector 3D'],
    recentTeacherFeedback: 'Top ranker in the batch with exceptional problem-solving speed. Advised to focus on error logs in Probability to prevent negative marking.'
  },
  {
    id: 'std_03',
    rollNumber: 'EXM-2026-104',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@apexacademy.edu',
    guardianName: 'Mr. Satish Deshmukh',
    guardianPhone: '+91 94230 11985',
    branchName: 'Delhi South Extension',
    batchId: 'batch_jee_pinnacle',
    batchName: 'JEE Pinnacle Super 30',
    targetExam: 'JEE Main',
    attendanceRate: 88,
    totalTestsAttempted: 12,
    avgScore: 178,
    rankInBatch: 14,
    weakTopics: ['Rotational Dynamics', 'Complex Numbers', 'Block Chemistry'],
    strongTopics: ['Kinematics', 'Chemical Bonding'],
    recentTeacherFeedback: 'Shows high motivation but rushes through multi-step mathematics calculations. Attendance in Sunday doubt counters strongly advised.'
  },
  {
    id: 'std_04',
    rollNumber: 'EXM-2026-121',
    name: 'Ananya Verma',
    email: 'ananya.v@apexacademy.edu',
    guardianName: 'Col. Rajesh Verma',
    guardianPhone: '+91 98110 55670',
    branchName: 'Hyderabad Madhapur Campus',
    batchId: 'batch_neet_achievers',
    batchName: 'NEET Achievers Batch A',
    targetExam: 'NEET-UG',
    attendanceRate: 98,
    totalTestsAttempted: 16,
    avgScore: 642,
    rankInBatch: 1,
    weakTopics: ['Physics Mechanics', 'Optics'],
    strongTopics: ['Human Physiology', 'Genetics', 'Ecology'],
    recentTeacherFeedback: 'Flawless performance in Biology and Chemistry (340+/360). Extra focus on numerical Physics formulas will assure a Top 500 All-India rank.'
  },
  {
    id: 'std_05',
    rollNumber: 'EXM-2026-159',
    name: 'Kabir Mehta',
    email: 'kabir.m@apexacademy.edu',
    guardianName: 'Mr. Arvind Mehta',
    guardianPhone: '+91 99800 77412',
    branchName: 'Bengaluru HSR Layout',
    batchId: 'batch_cat_elite',
    batchName: 'CAT IIM Callers Weekend',
    targetExam: 'CAT (IIM)',
    attendanceRate: 92,
    totalTestsAttempted: 10,
    avgScore: 114,
    rankInBatch: 3,
    weakTopics: ['Reading Comprehension Philosophy', 'Number Systems'],
    strongTopics: ['Logical Reasoning Grids', 'Algebra', 'Percentages'],
    recentTeacherFeedback: 'Solid logical intuition in DILR. Working on editorial passage reading speed will bring Verbal percentile to 99+.'
  }
];

export const INITIAL_TESTS: TestBlueprint[] = [
  {
    id: 'test_jee_all_india_01',
    title: 'All-India Full Syllabus Mock Test #04 (NTA Pattern)',
    examType: 'JEE Main',
    targetBatchIds: ['batch_jee_pinnacle'],
    totalDurationMinutes: 180,
    totalMarks: 300,
    cutoffPercentage: 45,
    status: 'Live',
    createdDate: '2026-03-01',
    instructions: [
      'Total duration of examination is 180 minutes.',
      'The clock will be set at the server. The countdown timer at the top displays remaining time.',
      'Marking Scheme: Section A (MCQs) +4 for correct, -1 for incorrect. Section B (Numerical) +4 for correct, 0 for incorrect.',
      'Calculators, mobile devices, and log tables are strictly prohibited.'
    ],
    sections: [
      {
        id: 'sec_phy',
        name: 'Physics',
        subject: 'Physics',
        totalQuestions: 2,
        markingScheme: { correct: 4, incorrect: -1, unattempted: 0 },
        questions: [
          INITIAL_QUESTIONS[0], // circular loop
          INITIAL_QUESTIONS[1]  // rolling sphere
        ]
      },
      {
        id: 'sec_chem',
        name: 'Chemistry',
        subject: 'Chemistry',
        totalQuestions: 2,
        markingScheme: { correct: 4, incorrect: -1, unattempted: 0 },
        questions: [
          INITIAL_QUESTIONS[2], // CFSE
          INITIAL_QUESTIONS[3]  // Gibbs
        ]
      },
      {
        id: 'sec_math',
        name: 'Mathematics',
        subject: 'Mathematics',
        totalQuestions: 2,
        markingScheme: { correct: 4, incorrect: -1, unattempted: 0 },
        questions: [
          INITIAL_QUESTIONS[4], // Definite integral
          INITIAL_QUESTIONS[5]  // 3D geometry
        ]
      }
    ],
    instituteBranding: {
      instituteName: 'APEX ACADEMY OF COMPETITIVE SCIENCES',
      branch: 'Central Campus, Kota (Rajasthan)',
      watermarkText: 'APEX ACADEMY CONFIDENTIAL',
      testCode: 'EXM-JEE-2026-M04'
    }
  },
  {
    id: 'test_neet_prep_02',
    title: 'NEET Target 720: Comprehensive Biology & Chemistry Drill',
    examType: 'NEET-UG',
    targetBatchIds: ['batch_neet_achievers'],
    totalDurationMinutes: 120,
    totalMarks: 240,
    cutoffPercentage: 55,
    status: 'Scheduled',
    createdDate: '2026-03-03',
    instructions: [
      'Test consists of 60 questions across Genetics, Evolution and Coordination Chemistry.',
      'Each question carries +4 marks. Incorrect answers result in -1 mark deduction.',
      'Review your responses before final submission.'
    ],
    sections: [
      {
        id: 'sec_neet_bio',
        name: 'Botany & Zoology',
        subject: 'Biology',
        totalQuestions: 1,
        markingScheme: { correct: 4, incorrect: -1, unattempted: 0 },
        questions: [INITIAL_QUESTIONS[6]]
      },
      {
        id: 'sec_neet_chem',
        name: 'Chemistry',
        subject: 'Chemistry',
        totalQuestions: 2,
        markingScheme: { correct: 4, incorrect: -1, unattempted: 0 },
        questions: [INITIAL_QUESTIONS[2], INITIAL_QUESTIONS[3]]
      }
    ],
    instituteBranding: {
      instituteName: 'APEX ACADEMY OF COMPETITIVE SCIENCES',
      branch: 'Medical Wing, Kota',
      watermarkText: 'APEX NEET DIVISION',
      testCode: 'EXM-NEET-2026-B02'
    }
  },
  {
    id: 'test_cbse_subjective_01',
    title: 'Class 12 Physics Pre-Board Subjective Assessment',
    examType: 'CBSE Class 12',
    targetBatchIds: ['batch_cbse_excel'],
    totalDurationMinutes: 90,
    totalMarks: 70,
    cutoffPercentage: 40,
    status: 'Completed',
    createdDate: '2026-02-28',
    instructions: [
      'All questions are compulsory. Internal choices are provided.',
      'Show clear diagrams and step-by-step derivations where asked.',
      'AI-assisted rubric evaluation is applied with faculty moderation.'
    ],
    sections: [
      {
        id: 'sec_cbse_long',
        name: 'Descriptive & Derivations',
        subject: 'Physics',
        totalQuestions: 1,
        markingScheme: { correct: 5, incorrect: 0, unattempted: 0, partialAllowed: true },
        questions: [INITIAL_QUESTIONS[8]]
      }
    ],
    instituteBranding: {
      instituteName: 'APEX SENIOR SECONDARY INSTITUTE',
      branch: 'South Extension, New Delhi',
      watermarkText: 'APEX PRE-BOARD EXAM',
      testCode: 'CBSE-PHY-2026-PB1'
    }
  }
];

export const INITIAL_ATTEMPT_RESULTS: TestAttemptResult[] = [
  {
    id: 'att_01',
    testId: 'test_jee_all_india_01',
    testTitle: 'All-India Full Syllabus Mock Test #04 (NTA Pattern)',
    studentId: 'std_01',
    studentName: 'Aarav Sharma',
    batchName: 'JEE Pinnacle Super 30',
    submittedAt: '2026-03-02 11:34 AM',
    totalMarksAwarded: 20,
    maxMarks: 24,
    percentage: 83.3,
    accuracy: 85.7,
    timeTakenSeconds: 3120,
    percentile: 98.6,
    rank: 2,
    totalParticipants: 32,
    answers: {
      q_phy_01: {
        questionId: 'q_phy_01',
        userAnswer: '1',
        status: 'answered',
        isCorrect: true,
        marksAwarded: 4,
        timeSpentSeconds: 95
      },
      q_phy_02: {
        questionId: 'q_phy_02',
        userAnswer: '5',
        status: 'answered',
        isCorrect: true,
        marksAwarded: 4,
        timeSpentSeconds: 140
      },
      q_chem_01: {
        questionId: 'q_chem_01',
        userAnswer: '0',
        status: 'answered',
        isCorrect: true,
        marksAwarded: 4,
        timeSpentSeconds: 52
      },
      q_chem_02: {
        questionId: 'q_chem_02',
        userAnswer: '0',
        status: 'answered',
        isCorrect: true,
        marksAwarded: 4,
        timeSpentSeconds: 48
      },
      q_math_01: {
        questionId: 'q_math_01',
        userAnswer: '0',
        status: 'answered',
        isCorrect: true,
        marksAwarded: 4,
        timeSpentSeconds: 68
      },
      q_math_02: {
        questionId: 'q_math_02',
        userAnswer: '4',
        status: 'answered',
        isCorrect: false,
        marksAwarded: 0,
        timeSpentSeconds: 185
      }
    },
    sectionScores: {
      'Physics': { scored: 8, total: 8, accuracy: 100 },
      'Chemistry': { scored: 8, total: 8, accuracy: 100 },
      'Mathematics': { scored: 4, total: 8, accuracy: 50 }
    }
  },
  {
    id: 'att_02',
    testId: 'test_cbse_subjective_01',
    testTitle: 'Class 12 Physics Pre-Board Subjective Assessment',
    studentId: 'std_01',
    studentName: 'Aarav Sharma',
    batchName: 'JEE Pinnacle Super 30',
    submittedAt: '2026-02-28 04:15 PM',
    totalMarksAwarded: 4.5,
    maxMarks: 5,
    percentage: 90,
    accuracy: 90,
    timeTakenSeconds: 780,
    percentile: 96.2,
    rank: 3,
    totalParticipants: 52,
    answers: {
      q_subj_01: {
        questionId: 'q_subj_01',
        userAnswer: 'According to Huygens Principle, each point on a primary wavefront acts as a new source of secondary wavelets. The envelope of these secondary spherical wavelets gives the new wavefront. For Young double slit, let S1 and S2 be separated by distance d. The path difference for ray reaching point P at distance y is delta_x = S2P - S1P = d sin theta = y*d / D. For constructive interference delta_x = n*lambda, so y_n = n*lambda*D / d. Fringe width beta = y_{n+1} - y_n = lambda*D / d.',
        status: 'answered',
        marksAwarded: 4.5,
        timeSpentSeconds: 520,
        aiEvaluation: {
          awardedMarks: 4.5,
          percentage: 90,
          conceptUnderstanding: 'Excellent',
          aiFeedback: 'Exceptional mathematical derivation with precise trigonometric approximation. Clear statement of secondary wavelets.',
          strengths: [
            'Rigorous derivation of path difference using small angle approximation',
            'Accurate definition of consecutive maxima spacing for fringe width'
          ],
          missedPoints: [
            'Could include a neat labeled sketch for complete board format 5/5'
          ],
          improvementTip: 'Always draw ray geometry diagrams in 5-mark board physics derivations.'
        }
      }
    },
    sectionScores: {
      'Physics': { scored: 4.5, total: 5, accuracy: 90 }
    }
  }
];

export const INITIAL_BRANCHES: CampusBranch[] = [
  {
    id: 'branch_kota',
    name: 'Kota Flagship Campus',
    code: 'KOT-01',
    city: 'Kota',
    state: 'Rajasthan',
    centerHead: 'Prof. Rameshwar Vyas (Ex-IIT Delhi)',
    totalStudents: 520,
    activeBatches: 12,
    overallAvgScore: 218,
    cutoffClearanceRate: 84.5,
    topScore: 288,
    topPercentileCount: 42,
    subjectAverages: {
      physics: 74,
      chemistry: 78,
      mathematics: 66,
    },
    scoreDistribution: {
      topTier: 35,
      proficient: 42,
      average: 18,
      needSupport: 5,
    },
    attendanceRate: 96.4,
    status: 'doing_good',
    healthScore: 95,
    facultyCount: 24,
    facultyHealthScore: 96,
    studentSatisfaction: 94,
    syllabusCompletion: 92,
    statusReason: 'Top academic accuracy, 0 syllabus delay, stellar mock test participation.',
    openIssuesCount: 0,
  },
  {
    id: 'branch_hyderabad',
    name: 'Hyderabad Madhapur Campus',
    code: 'HYD-02',
    city: 'Hyderabad',
    state: 'Telangana',
    centerHead: 'K. Venkateswara Rao (Senior Faculty)',
    totalStudents: 410,
    activeBatches: 9,
    overallAvgScore: 212,
    cutoffClearanceRate: 81.0,
    topScore: 282,
    topPercentileCount: 36,
    subjectAverages: {
      physics: 72,
      chemistry: 75,
      mathematics: 65,
    },
    scoreDistribution: {
      topTier: 31,
      proficient: 43,
      average: 20,
      needSupport: 6,
    },
    attendanceRate: 94.7,
    status: 'doing_good',
    healthScore: 92,
    facultyCount: 18,
    facultyHealthScore: 93,
    studentSatisfaction: 91,
    syllabusCompletion: 89,
    statusReason: 'Strong Maths & Chemistry scores; robust CBT mock test compliance.',
    openIssuesCount: 1,
  },
  {
    id: 'branch_delhi',
    name: 'Delhi South Extension Center',
    code: 'DEL-03',
    city: 'New Delhi',
    state: 'NCR Delhi',
    centerHead: 'Dr. Sunita Aggarwal (Ph.D Physics)',
    totalStudents: 380,
    activeBatches: 8,
    overallAvgScore: 196,
    cutoffClearanceRate: 76.2,
    topScore: 274,
    topPercentileCount: 28,
    subjectAverages: {
      physics: 68,
      chemistry: 71,
      mathematics: 57,
    },
    scoreDistribution: {
      topTier: 26,
      proficient: 44,
      average: 22,
      needSupport: 8,
    },
    attendanceRate: 91.8,
    status: 'doing_good',
    healthScore: 88,
    facultyCount: 16,
    facultyHealthScore: 90,
    studentSatisfaction: 87,
    syllabusCompletion: 86,
    statusReason: 'Consistent test attendance; active parental WhatsApp engagement.',
    openIssuesCount: 0,
  },
  {
    id: 'branch_pune',
    name: 'Pune Shivaji Nagar Campus',
    code: 'PUN-04',
    city: 'Pune',
    state: 'Maharashtra',
    centerHead: 'Prof. Milind Joshi (Ex-COEP)',
    totalStudents: 310,
    activeBatches: 7,
    overallAvgScore: 204,
    cutoffClearanceRate: 78.4,
    topScore: 279,
    topPercentileCount: 26,
    subjectAverages: {
      physics: 70,
      chemistry: 73,
      mathematics: 61,
    },
    scoreDistribution: {
      topTier: 28,
      proficient: 45,
      average: 20,
      needSupport: 7,
    },
    attendanceRate: 93.5,
    status: 'doing_good',
    healthScore: 89,
    facultyCount: 14,
    facultyHealthScore: 89,
    studentSatisfaction: 88,
    syllabusCompletion: 87,
    statusReason: 'High retention rate in engineering batches; prompt rubric evaluations.',
    openIssuesCount: 1,
  },
  {
    id: 'branch_bangalore',
    name: 'Bengaluru HSR Layout Campus',
    code: 'BLR-05',
    city: 'Bengaluru',
    state: 'Karnataka',
    centerHead: 'Anand Kulkarni (Ex-IIM Bangalore)',
    totalStudents: 320,
    activeBatches: 7,
    overallAvgScore: 188,
    cutoffClearanceRate: 72.8,
    topScore: 268,
    topPercentileCount: 22,
    subjectAverages: {
      physics: 64,
      chemistry: 69,
      mathematics: 55,
    },
    scoreDistribution: {
      topTier: 22,
      proficient: 46,
      average: 24,
      needSupport: 8,
    },
    attendanceRate: 93.2,
    status: 'doing_good',
    healthScore: 84,
    facultyCount: 15,
    facultyHealthScore: 86,
    studentSatisfaction: 85,
    syllabusCompletion: 84,
    statusReason: 'Good tech integration with OMR scanning and hybrid doubt sessions.',
    openIssuesCount: 0,
  },
  {
    id: 'branch_mumbai',
    name: 'Mumbai Andheri West Center',
    code: 'MUM-06',
    city: 'Mumbai',
    state: 'Maharashtra',
    centerHead: 'Kavita Menon (Ex-TIFR Researcher)',
    totalStudents: 350,
    activeBatches: 8,
    overallAvgScore: 192,
    cutoffClearanceRate: 74.0,
    topScore: 271,
    topPercentileCount: 24,
    subjectAverages: {
      physics: 66,
      chemistry: 70,
      mathematics: 56,
    },
    scoreDistribution: {
      topTier: 24,
      proficient: 44,
      average: 24,
      needSupport: 8,
    },
    attendanceRate: 91.5,
    status: 'doing_good',
    healthScore: 85,
    facultyCount: 17,
    facultyHealthScore: 84,
    studentSatisfaction: 83,
    syllabusCompletion: 83,
    statusReason: 'Strong medical batch scores; steady weekly test submissions.',
    openIssuesCount: 1,
  },
  {
    id: 'branch_patna',
    name: 'Patna Kankarbagh Center',
    code: 'PAT-07',
    city: 'Patna',
    state: 'Bihar',
    centerHead: 'Alok Kumar Shrivastava (Senior Faculty)',
    totalStudents: 290,
    activeBatches: 6,
    overallAvgScore: 148,
    cutoffClearanceRate: 51.2,
    topScore: 232,
    topPercentileCount: 11,
    subjectAverages: {
      physics: 48,
      chemistry: 54,
      mathematics: 46,
    },
    scoreDistribution: {
      topTier: 11,
      proficient: 31,
      average: 32,
      needSupport: 26,
    },
    attendanceRate: 79.4,
    status: 'doing_not_good',
    healthScore: 56,
    facultyCount: 11,
    facultyHealthScore: 58,
    studentSatisfaction: 62,
    syllabusCompletion: 68,
    statusReason: 'Subjective paper evaluation delayed by 5 days; Physics mock accuracy critically low (48%).',
    openIssuesCount: 2,
  },
  {
    id: 'branch_lucknow',
    name: 'Lucknow Hazratganj Center',
    code: 'LKO-08',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    centerHead: 'Mohd. Tariq Siddiqui (M.Tech IIT Kanpur)',
    totalStudents: 260,
    activeBatches: 6,
    overallAvgScore: 154,
    cutoffClearanceRate: 54.8,
    topScore: 238,
    topPercentileCount: 12,
    subjectAverages: {
      physics: 52,
      chemistry: 49,
      mathematics: 53,
    },
    scoreDistribution: {
      topTier: 12,
      proficient: 34,
      average: 30,
      needSupport: 24,
    },
    attendanceRate: 82.1,
    status: 'doing_not_good',
    healthScore: 59,
    facultyCount: 10,
    facultyHealthScore: 54,
    studentSatisfaction: 64,
    syllabusCompletion: 71,
    statusReason: 'Senior Chemistry Faculty resignation created vacancy in JEE Droppers; test backlog of 2 exams.',
    openIssuesCount: 2,
  },
  {
    id: 'branch_kolkata',
    name: 'Kolkata Salt Lake Center',
    code: 'KOL-09',
    city: 'Kolkata',
    state: 'West Bengal',
    centerHead: 'Subrata Mukherjee (Ph.D Physical Sciences)',
    totalStudents: 280,
    activeBatches: 6,
    overallAvgScore: 151,
    cutoffClearanceRate: 53.4,
    topScore: 241,
    topPercentileCount: 14,
    subjectAverages: {
      physics: 47,
      chemistry: 55,
      mathematics: 49,
    },
    scoreDistribution: {
      topTier: 13,
      proficient: 32,
      average: 31,
      needSupport: 24,
    },
    attendanceRate: 80.5,
    status: 'doing_not_good',
    healthScore: 58,
    facultyCount: 12,
    facultyHealthScore: 61,
    studentSatisfaction: 63,
    syllabusCompletion: 70,
    statusReason: '18 students in Batch B02 have severe accuracy dip (<36%); parent complaints regarding mock feedback.',
    openIssuesCount: 2,
  },
  {
    id: 'branch_jaipur',
    name: 'Jaipur Malviya Nagar Center',
    code: 'JPR-10',
    city: 'Jaipur',
    state: 'Rajasthan',
    centerHead: 'Dhirendra Singh Rathore (Ex-ISRO Engineer)',
    totalStudents: 270,
    activeBatches: 5,
    overallAvgScore: 162,
    cutoffClearanceRate: 58.0,
    topScore: 248,
    topPercentileCount: 15,
    subjectAverages: {
      physics: 54,
      chemistry: 57,
      mathematics: 51,
    },
    scoreDistribution: {
      topTier: 15,
      proficient: 35,
      average: 28,
      needSupport: 22,
    },
    attendanceRate: 81.2,
    status: 'doing_not_good',
    healthScore: 62,
    facultyCount: 11,
    facultyHealthScore: 65,
    studentSatisfaction: 67,
    syllabusCompletion: 74,
    statusReason: 'Attendance drop in evening batches (-18% last 14 days); CBT test integrity anomalies flagged.',
    openIssuesCount: 2,
  },
];

export const INITIAL_ADMIN_ISSUES: AdminIssue[] = [
  {
    id: 'issue_fac_01',
    centerId: 'branch_patna',
    centerName: 'Patna Kankarbagh Center',
    level: 'faculty',
    severity: 'critical',
    title: 'Subjective Paper Evaluation Overdue (Class 12 Physics Pre-Board)',
    description: 'Faculty grading backlog: 52 subjective answer copies pending for >5 days. Students waiting for remedial feedback before board exams.',
    affectedCount: 52,
    reportedDate: '2026-03-03',
    status: 'open',
    suggestedFix: 'Reassign 30 answer sheets to Central Kota Evaluator pool or activate AI-assisted Rubric Batch Scoring.',
    availableActions: [
      'Reassign copies to Central Kota Faculty',
      'Run Automated AI Rubric Batch Grading',
      'Issue Urgent 24h Deadline Notice to Center Head'
    ]
  },
  {
    id: 'issue_fac_02',
    centerId: 'branch_lucknow',
    centerName: 'Lucknow Hazratganj Center',
    level: 'faculty',
    severity: 'critical',
    title: 'Senior Chemistry Faculty Vacancy in JEE Droppers Batch',
    description: 'Faculty resignation left 64 Dropper students without an Organic Chemistry teacher. Syllabus is 14 days behind schedule.',
    affectedCount: 64,
    reportedDate: '2026-03-01',
    status: 'open',
    suggestedFix: 'Deploy Kota Senior Guest Faculty via hybrid live studio, and unlock Eximo AI masterclass archive.',
    availableActions: [
      'Assign Central Kota Guest Faculty (Hybrid Live)',
      'Unlock AI Remedial Video Modules for Batch',
      'Authorize Emergency Faculty Hiring Bonus'
    ]
  },
  {
    id: 'issue_fac_03',
    centerId: 'branch_pune',
    centerName: 'Pune Shivaji Nagar Campus',
    level: 'faculty',
    severity: 'moderate',
    title: 'Calculus Syllabus Lag (-15% behind JEE Main Target)',
    description: 'Maths faculty pacing was delayed due to heavy student doubts in Coordinate Geometry.',
    affectedCount: 45,
    reportedDate: '2026-03-04',
    status: 'open',
    suggestedFix: 'Schedule Sunday 4-hour Marathon Booster session with co-faculty support.',
    availableActions: [
      'Schedule 2 Sunday Marathon Booster Lectures',
      'Assign Co-Faculty for Doubt Support',
      'Approve Adjusted Lesson Plan'
    ]
  },
  {
    id: 'issue_std_01',
    centerId: 'branch_kolkata',
    centerName: 'Kolkata Salt Lake Center',
    level: 'student',
    severity: 'critical',
    title: '18 Students Severe Score Dip (<35% Accuracy) in Physics',
    description: 'Rotational Dynamics & Electromagnetism mock test showed 18 students failing negative marking cutoffs. Risk of parent churn.',
    affectedCount: 18,
    reportedDate: '2026-03-04',
    status: 'open',
    suggestedFix: 'Dispatch customized AI remedial drill sets directly to student portals and alert academic counselors.',
    availableActions: [
      'Dispatch AI Remedial Workbooks to Students',
      'Send Automated WhatsApp Diagnostic to Parents',
      'Book 1-on-1 Academic Counseling Sessions'
    ]
  },
  {
    id: 'issue_std_02',
    centerId: 'branch_jaipur',
    centerName: 'Jaipur Malviya Nagar Center',
    level: 'student',
    severity: 'critical',
    title: 'Chronic Attendance Drop (-18.8%) in Evening Repeater Batch',
    description: '34 students have missed 4+ consecutive test review lectures. Test clearance rates dropping sharply.',
    affectedCount: 34,
    reportedDate: '2026-03-02',
    status: 'open',
    suggestedFix: 'Trigger automated WhatsApp attendance alerts to guardians and freeze mock exam tokens pending parent contact.',
    availableActions: [
      'Dispatch WhatsApp & SMS Notice to Guardians',
      'Schedule Mandatory Parent-Teacher Digital Meet',
      'Offer Flexible Morning Alternate Batch Slot'
    ]
  },
  {
    id: 'issue_std_03',
    centerId: 'branch_hyderabad',
    centerName: 'Hyderabad Madhapur Campus',
    level: 'student',
    severity: 'warning',
    title: 'CBT Simulator Exam Irregularity (Rapid Guessing Pattern)',
    description: '6 students completed 75 questions in under 22 minutes with <15% accuracy, indicating random guessing behavior.',
    affectedCount: 6,
    reportedDate: '2026-03-05',
    status: 'open',
    suggestedFix: 'Reset exam attempt with strict pacing minimums (30s/question) and mandate mentor review.',
    availableActions: [
      'Reset CBT Attempt with Minimum Time Lock',
      'Flag Roll Numbers for Proctored Lab Testing',
      'Assign CBT Exam Strategy Coaching'
    ]
  },
  {
    id: 'issue_std_04',
    centerId: 'branch_mumbai',
    centerName: 'Mumbai Andheri West Center',
    level: 'student',
    severity: 'warning',
    title: 'Doubt Ticket Queue Exceeding 48 Hours SLA (58 Open Doubts)',
    description: 'NEET Biology and Physics students waiting over 2 days for doubt answers, leading to drop in mock test confidence.',
    affectedCount: 58,
    reportedDate: '2026-03-04',
    status: 'open',
    suggestedFix: 'Activate 24/7 Eximo AI Doubt Solver Bot on student portal and allocate 2 Central TAs for 48 hours.',
    availableActions: [
      'Activate 24/7 AI Instant Doubt Bot',
      'Allocate Central Teaching Assistant Pool',
      'Host Live Weekend Doubt Clearance Marathon'
    ]
  },
  {
    id: 'issue_fac_04',
    centerId: 'branch_patna',
    centerName: 'Patna Kankarbagh Center',
    level: 'faculty',
    severity: 'warning',
    title: 'Missing CBT Blueprint for Upcoming Sunday All-India Test',
    description: 'Center faculty failed to submit their regional mock test blueprint 48 hours prior to test window.',
    affectedCount: 290,
    reportedDate: '2026-03-05',
    status: 'open',
    suggestedFix: 'Auto-sync Central Kota Standard JEE Mock Test Blueprint to Patna Center roster.',
    availableActions: [
      'Auto-Deploy Central All-India Blueprint',
      'Issue Non-Compliance Warning to Center Lead',
      'Allow 12-Hour Extension with Standard Template'
    ]
  }
];

export const SAMPLE_OMR_SCANS: OmrScanResult[] = [
  {
    scanId: 'omr_scan_01',
    studentRollNumber: 'EXM-2026-042',
    studentName: 'Aarav Sharma',
    testCode: 'JEE-MOCK-04',
    testTitle: 'All-India Full Syllabus Mock Test #04 (NTA Pattern)',
    scannedTimestamp: '2026-03-05 17:42',
    confidenceScore: 99.7,
    totalQuestions: 20,
    attemptedCount: 18,
    correctCount: 15,
    incorrectCount: 3,
    blankCount: 2,
    ambiguousCount: 0,
    totalMarksAwarded: 57,
    maxMarks: 80,
    percentage: 71.25,
    questions: [
      { questionNumber: 1, markedOption: 'B', confidence: 0.99, correctAnswer: 'B', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 2, markedOption: 'A', confidence: 0.98, correctAnswer: 'A', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 3, markedOption: 'C', confidence: 0.99, correctAnswer: 'C', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 4, markedOption: 'A', confidence: 0.97, correctAnswer: 'A', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 5, markedOption: 'D', confidence: 0.99, correctAnswer: 'D', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 6, markedOption: 'B', confidence: 0.96, correctAnswer: 'C', isCorrect: false, status: 'incorrect', marksAwarded: -1 },
      { questionNumber: 7, markedOption: 'A', confidence: 0.99, correctAnswer: 'A', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 8, markedOption: 'C', confidence: 0.99, correctAnswer: 'C', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 9, markedOption: 'BLANK', confidence: 1.0, correctAnswer: 'B', isCorrect: false, status: 'blank', marksAwarded: 0 },
      { questionNumber: 10, markedOption: 'D', confidence: 0.98, correctAnswer: 'D', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 11, markedOption: 'A', confidence: 0.99, correctAnswer: 'A', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 12, markedOption: 'C', confidence: 0.95, correctAnswer: 'D', isCorrect: false, status: 'incorrect', marksAwarded: -1 },
      { questionNumber: 13, markedOption: 'B', confidence: 0.99, correctAnswer: 'B', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 14, markedOption: 'D', confidence: 0.99, correctAnswer: 'D', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 15, markedOption: 'A', confidence: 0.98, correctAnswer: 'A', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 16, markedOption: 'C', confidence: 0.99, correctAnswer: 'C', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 17, markedOption: 'BLANK', confidence: 1.0, correctAnswer: 'A', isCorrect: false, status: 'blank', marksAwarded: 0 },
      { questionNumber: 18, markedOption: 'B', confidence: 0.98, correctAnswer: 'B', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 19, markedOption: 'C', confidence: 0.97, correctAnswer: 'A', isCorrect: false, status: 'incorrect', marksAwarded: -1 },
      { questionNumber: 20, markedOption: 'D', confidence: 0.99, correctAnswer: 'D', isCorrect: true, status: 'correct', marksAwarded: 4 },
    ],
  },
  {
    scanId: 'omr_scan_02',
    studentRollNumber: 'EXM-2026-104',
    studentName: 'Rohan Deshmukh',
    testCode: 'JEE-MOCK-04',
    testTitle: 'All-India Full Syllabus Mock Test #04 (NTA Pattern)',
    scannedTimestamp: '2026-03-05 17:48',
    confidenceScore: 96.4,
    totalQuestions: 20,
    attemptedCount: 16,
    correctCount: 10,
    incorrectCount: 5,
    blankCount: 4,
    ambiguousCount: 1,
    totalMarksAwarded: 35,
    maxMarks: 80,
    percentage: 43.75,
    questions: [
      { questionNumber: 1, markedOption: 'B', confidence: 0.99, correctAnswer: 'B', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 2, markedOption: 'B', confidence: 0.94, correctAnswer: 'A', isCorrect: false, status: 'incorrect', marksAwarded: -1 },
      { questionNumber: 3, markedOption: 'DOUBLE_MARKED', confidence: 0.62, correctAnswer: 'C', isCorrect: false, status: 'ambiguous', marksAwarded: 0 },
      { questionNumber: 4, markedOption: 'A', confidence: 0.98, correctAnswer: 'A', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 5, markedOption: 'C', confidence: 0.92, correctAnswer: 'D', isCorrect: false, status: 'incorrect', marksAwarded: -1 },
      { questionNumber: 6, markedOption: 'BLANK', confidence: 1.0, correctAnswer: 'C', isCorrect: false, status: 'blank', marksAwarded: 0 },
      { questionNumber: 7, markedOption: 'A', confidence: 0.99, correctAnswer: 'A', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 8, markedOption: 'C', confidence: 0.99, correctAnswer: 'C', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 9, markedOption: 'BLANK', confidence: 1.0, correctAnswer: 'B', isCorrect: false, status: 'blank', marksAwarded: 0 },
      { questionNumber: 10, markedOption: 'D', confidence: 0.98, correctAnswer: 'D', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 11, markedOption: 'B', confidence: 0.91, correctAnswer: 'A', isCorrect: false, status: 'incorrect', marksAwarded: -1 },
      { questionNumber: 12, markedOption: 'D', confidence: 0.99, correctAnswer: 'D', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 13, markedOption: 'A', confidence: 0.92, correctAnswer: 'B', isCorrect: false, status: 'incorrect', marksAwarded: -1 },
      { questionNumber: 14, markedOption: 'D', confidence: 0.99, correctAnswer: 'D', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 15, markedOption: 'BLANK', confidence: 1.0, correctAnswer: 'A', isCorrect: false, status: 'blank', marksAwarded: 0 },
      { questionNumber: 16, markedOption: 'C', confidence: 0.99, correctAnswer: 'C', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 17, markedOption: 'BLANK', confidence: 1.0, correctAnswer: 'A', isCorrect: false, status: 'blank', marksAwarded: 0 },
      { questionNumber: 18, markedOption: 'B', confidence: 0.98, correctAnswer: 'B', isCorrect: true, status: 'correct', marksAwarded: 4 },
      { questionNumber: 19, markedOption: 'B', confidence: 0.94, correctAnswer: 'A', isCorrect: false, status: 'incorrect', marksAwarded: -1 },
      { questionNumber: 20, markedOption: 'D', confidence: 0.99, correctAnswer: 'D', isCorrect: true, status: 'correct', marksAwarded: 4 },
    ],
  },
];
